name: open_agent

services:

    app:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: open_agent
      ports:
        - "8000:8000"
      env_file:
        - .env
      volumes:
        - .:/app
