name: open_agent

services:

    app:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: open_agent
      ports:
        - "8000:8000"
      env_file:
        - .env
      volumes:
        - .:/app

    n8n:
      image: n8nio/n8n
      ports:
        - "5678:5678"
      volumes:
        - n8n_data:/home/node/.n8n

volumes: 
  n8n_data:
